<?php

namespace MonthBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DayRepository extends EntityRepository
{

  private function dayRepo(){
    return $this->getEntityManager()->getRepository('MonthBundle:Day');
  }

  public function saveDay($day){

  }

  public function saveDayRange($dayRange){

  }

  public function allDaysForMonth($start, $end){

    $qb = $this->dayRepo()->createQueryBuilder('d');
    $result = $qb->where('d.day BETWEEN :start AND :end')
      ->setParameter('start', $start->format('Y-m-d'))
      ->setParameter('end', $end->format('Y-m-d'))
      ->orderBy('d.day', 'ASC')->getQuery()->getResult();
    return $result;

  }

  public function updateDay($day){

  }

  public function updateDayRange($dayRange){

  }


}
