services:
#    month.example:
#        class: MonthBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     json.class:
       class: MonthBundle\Utils\JsonParser
       arguments: []
